version: '3.9'

services:
  api:
    build: "api/"
    restart: "on-failure"
    expose: 
      - "8080"

  proxy:
    build: "proxy/"
    restart: "on-failure"
    expose: 
      - "80"
    ports: 
      - "80:80"
